### ISSUE TITLE
Multiline string indentation

### ISSUE THREAD

**Issue by jbw** [qoobaa/ruby-electric#1]
Doing { RET } indents braces next to each other, but %{ RET } does not which makes it difficult to do multiline strings using %{ }.

**Comment by qoobaa** [comment]
I think it's more ruby-mode problem that ruby-electric-mode problem. Electric mode doesn't do indentation.

**Comment by jbw** [comment]
Yeah sorry, I looked at your code and came to that conclusion. 

EDIT: closing.
