### ISSUE TITLE
Got different version from MELPA

### ISSUE THREAD

**Issue by terotil** [qoobaa/ruby-electric#10]
As advertised in `README.md`, I added MELPA repo and installed `ruby-electric`. My emacs is 24.3.1 from Debian Jessie repositories, and no other repos added before this. When I turned on `ruby-electric-mode`, I got an error saying function `ruby-insert-end` was missing. Looking into the source of the installed package revealed me that it wasn't this (https://github.com/qoobaa/ruby-electric/) at all, but https://github.com/knu/ruby-electric.el

The receipe in MELPA repos seems to be pointing under Ruby SVN repos
https://github.com/milkypostman/melpa/blob/master/recipes/ruby-electric

Whats the relation between this and Akinori's fork?  Is there any ongoing effort to merge them or are they already too far away from each other?

Apparently either MELPA receipe or README.md should be changed to make them consistent.

**Comment by qoobaa** [comment]
I think the current version lies in the Ruby repository. I don't maintain this repository any more.

http://melpa.milkbox.net/#/ruby-electric

I don't see any references to my repo.

**Comment by terotil** [comment]
You are absolutely right. However, this repo is top hit when you google for "ruby-electric" and `README.md` advertises installing via MELPA, which (somewhat surprisingly) does not install this version, but another one.

I think it would be really nice of you, if you'd mention in the readme that MELPA & Ruby bundled version is different, or just plain not talk about MELPA at all. I can throw in a PR if you want.

**Comment by qoobaa** [comment]
Done. Thanks.
