### ISSUE TITLE
Inserting brackets causes error

### ISSUE THREAD

**Issue by arbox** [qoobaa/ruby-electric#4]
While using electric mode, inserting pair signs (e.g. brackets) causes the following error:

```
Symbol's value as variable is void: last-command-char
```

It is an issue of Emacs 24: 

```
GNU Emacs 24.2.50.1 (x86_64-pc-linux-gnu, GTK+ Version 3.4.2) of 2012-08-25 on hamsa, modified by Debian
```

A possible workaround without the ruby electric mode found here:
http://blog.livedoor.jp/ooboofo3/archives/53748087.html

**Comment by qoobaa** [comment]
It was fixed by replacing `last-command-char` to `last-commant-event`.
