### ISSUE TITLE
ruby-electric-mode error (scan-error "Containing expression ends prematurely" 162 162)

### ISSUE THREAD

**Issue by stardiviner** [qoobaa/ruby-electric#7]
as the title.

When I press <kbd>SPACE</kbd> atfer `class`.
then Emacs shows this error message.

**Comment by qoobaa** [comment]
Can you try using ruby-electric from MELPA repository?

http://melpa.milkbox.net/#/ruby-electric

**Comment by stardiviner** [comment]
I'm using el-get, and I write a recipe with elpa source to install ruby-electric.
(I'm curious why use MELPA instead of this github repo? Did you stop updating this repo?)

The custom recipe is here:

``` lisp
(:name ruby-electric
       :description "Electric commands editing for ruby files"
       :type elpa
       ;; :prepare
       ;; (progn
       ;;   (autoload 'ruby-electric-mode "ruby-electric" nil t))
       )
```

Is this recipe correct?

**Comment by qoobaa** [comment]
I'm not sure if it's correct, I haven't done it for a while. A year ago someone asked me to merge ruby-electric.el back to Ruby repo. I think the most current version maintained by community is kept there now.

**Comment by stardiviner** [comment]
Thanks, I will check it out.
